import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'de' | 'rs' | 'it' | 'fr' | 'es' | 'pt' | 'jp' | 'ru';

export interface LanguageConfig {
  code: Language;
  name: string;
  flag: string;
  emoji: string;
}

export const LANGUAGES: LanguageConfig[] = [
  { code: 'en', name: 'English', flag: '🇺🇸', emoji: '🇺🇸' },
  { code: 'de', name: 'German', flag: '🇩🇪', emoji: '🇩🇪' },
  { code: 'rs', name: 'Serbian', flag: '🇷🇸', emoji: '🇷🇸' },
  { code: 'it', name: 'Italian', flag: '🇮🇹', emoji: '🇮🇹' },
  { code: 'fr', name: 'French', flag: '🇫🇷', emoji: '🇫🇷' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸', emoji: '🇪🇸' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹', emoji: '🇵🇹' },
  { code: 'jp', name: 'Japanese', flag: '🇯🇵', emoji: '🇯🇵' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺', emoji: '🇷🇺' },
];

export interface Translation {
  [key: string]: string;
}

export const translations: Record<Language, Translation> = {
  en: {
    'welcome.title': 'Welcome to GRP Database',
    'welcome.description': 'GRP Database is an unofficial community hub designed to make GTA Roleplay easier and more enjoyable. Our goal is to gather valuable information in one place — from item values and clothing options to beginner tips and guides — helping players quickly find what they need while playing on the server.',
    'welcome.disclaimer': 'GRP Database is NOT official or affiliated with the developers of the game.',
    'admin.access': 'Admin Access',
    'admin.panel': 'Admin Panel',
    'admin.login': 'Admin Login',
    'admin.description': 'You are currently logged in as an administrator. Access the admin panel to manage the database and system settings.',
    'admin.login_description': 'Are you an administrator? Access the admin panel to manage the database and system settings.',
    'values.title': 'Item Values',
    'values.description': 'Find current market values for vehicles, clothing, and items.',
    'battlepass.title': 'Battlepass',
    'battlepass.description': 'Track your battlepass progress and rewards.',
    'beginner.title': 'Beginner Help',
    'beginner.description': 'Essential guides for new players.',
    'bunker.title': 'Bunker Help',
    'bunker.description': 'Bunker management and optimization guides.',
    'events.title': 'Events',
    'events.description': 'Server events and activities.',
    'lifeinvader.title': 'LifeInvader Templates',
    'lifeinvader.description': 'Pre-formatted ad templates for LifeInvader.',
    'improvements.title': 'Improvements',
    'improvements.description': 'Suggest improvements and report bugs.',
    'suggestions.title': 'Suggestions',
    'suggestions.description': 'Submit your suggestions for the database.',
    'treasure.title': 'Treasure Helper',
    'treasure.description': 'Find treasure locations and rewards.',
    'pet.title': 'Pet Timer',
    'pet.description': 'Track your pet feeding schedule.',
    'ai.format_my_ad': 'Format My Ad',
    'ai.description': 'Use AI to format your ads according to policy.',
    'community.title': 'Community-Driven Platform',
    'community.built_by_players': '🤝 Built by Players, for Players',
    'community.built_description': 'This platform is maintained and updated by the GRP Database community. All values, templates, and features are contributed by active players who understand the market dynamics and community needs.',
    'community.real_time_data': '📊 Real-Time Market Data',
    'community.data_description': 'Get accurate, up-to-date market values for vehicles, clothing, and items. Our community ensures the data reflects current market conditions and helps you make informed trading decisions.',
    'navigation.categories': 'Categories',
    'how_to_join': 'How to Join?',
    'notification.new_update': 'New Update!',
    'notification.close': 'Close popup',
    'community.ai_powered': '🎯 AI-Powered Assistance',
    'community.ai_description': 'Our advanced AI assistant learns from community feedback to provide better ad formatting and suggestions. Every correction helps improve the system for everyone.',
    'community.continuous_improvement': '🔄 Continuous Improvement',
    'community.improvement_description': 'The platform evolves based on community feedback and needs. New features, categories, and improvements are regularly added to enhance your experience.',
    'community.tip': '💡 Tip:',
    'community.tip_text': 'Found an outdated value or have a suggestion? Contact robthemaster on discord to help improve the platform for everyone!',
    'categories.cars': 'Cars',
    'categories.boats': 'Boats',
    'categories.planes': 'Planes',
    'categories.helicopters': 'Helicopters',
    'categories.clothing_list': 'Clothing List',
    'categories.masks': 'Masks',
    'categories.luminous_clothing': 'Luminous Clothing',
    'categories.items': 'Items',
    'categories.motorcycles': 'Motorcycles',
    'categories.illegal_items': 'Illegal Items',
    'categories.cropped_collection_shirts': 'Cropped Collection Shirts',
    'categories.denim_jackets': 'Denim Jackets',
    'navigation.home': 'Home',
    'navigation.logout': 'Logout',
    'page_titles.battlepass': 'Battlepass',
    'page_titles.bunker_help': 'Bunker Help',
    'page_titles.pet_timer': 'Pet Timer',
    'page_titles.lifeinvader': 'LifeInvader',
    'page_titles.suggestions': 'Suggestions',
    'page_titles.improvements': 'Improvements',
    'page_titles.admin_panel': 'Admin Panel',
    'events.school.title': 'School Event',
    'events.school.description': 'Chemistry color mixer for school events.',
    'events.school.chemistry': 'Chemistry',
    'footer.description': 'Providing information, tools, and analytics for the GTA Roleplay trading, gaming, and related communities.',
    'footer.grand_roleplay_trademark': 'Grand Roleplay and its various marks and logos are trademarks of Grand Roleplay.',
    'footer.gta_v_trademark': 'Grand Theft Auto V is a trademark of Take-Two Interactive Software Inc.',
    'footer.disclaimer': 'GRP Database is not endorsed, sponsored, or affiliated with GTA V and Grand Roleplay.',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.contact': 'Contact',
    'privacy.title': 'Privacy Policy',
    'privacy.data_collection.title': 'Data Collection',
    'privacy.data_collection.description': 'GRP Database does not require user accounts or personal information to use the website. We do not set any tracking cookies.',
    'privacy.data_collection.analytics': 'We use privacy-friendly analytics (powered by Vercel) to understand how visitors use the site. This may include anonymized information such as:',
    'privacy.data_collection.browser_type': 'Browser type',
    'privacy.data_collection.pages_visited': 'Pages visited',
    'privacy.data_collection.approximate_location': 'Approximate location (based on IP address)',
    'privacy.data_collection.ip_addresses': 'IP addresses are processed only for the purpose of generating usage statistics and are anonymized. We do not use them to personally identify visitors.',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.description': 'GRP Database does not use tracking cookies.',
    'privacy.data_sharing.title': 'Data Sharing',
    'privacy.data_sharing.description': 'We do not sell, share, or disclose your information to third parties. Analytics data is only used to improve the website.',
    'privacy.contact.title': 'Contact',
    'privacy.contact.description': 'If you have questions about this Privacy Policy, please reach out via the contact form or community channels.',
    'contact.title': 'Contact Us',
    'contact.description': 'Have a question or suggestion? We\'d love to hear from you!',
    'contact.email_label': 'Email Address',
    'contact.email_placeholder': 'your.email@example.com',
    'contact.subject_label': 'Subject',
    'contact.subject_placeholder': 'What is this about?',
    'contact.message_label': 'Message',
    'contact.message_placeholder': 'Tell us what\'s on your mind...',
    'contact.send_button': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success_message': 'Thank you! Your message has been sent successfully.',
    'contact.error_message': 'Sorry, there was an error sending your message. Please try again.',
    'car_customizer.title': 'Car Customizer',
    'car_customizer.description': 'Customize your dream car with real-life inspired models from GTA V. Choose colors, parts, and accessories to create your perfect ride.',
    'car_customizer.select_car': 'Select Car Model',
    'car_customizer.customize': 'Customize Your Car',
    'car_customizer.color': 'Color',
    'car_customizer.parts': 'Parts',
    'car_customizer.spoiler': 'Spoiler',
    'car_customizer.neon': 'Neon Lights',
    'car_customizer.tint': 'Window Tint',
    'car_customizer.no_tint': 'No Tint',
    'car_customizer.light_tint': 'Light Tint',
    'car_customizer.medium_tint': 'Medium Tint',
    'car_customizer.dark_tint': 'Dark Tint',
    'car_customizer.reset': 'Reset',
    'car_customizer.save': 'Save Design',
    'car_customizer.total_price': 'Total Price',
    'car_customizer.price_note': 'Prices are based on in-game values and may vary',
    'car_customizer.privacy_notice_title': 'Privacy Notice',
    'car_customizer.privacy_notice_text': 'Your customizations are stored locally in your browser and are not sent to our servers. No personal data is collected during customization.',
    'car_customizer.preview': '3D Preview',
    'car_customizer.custom_color': 'Custom Color',
    'car_customizer.underglow': 'Underglow',
  },
  de: {
    'welcome.title': 'Willkommen bei GRP Database',
    'welcome.description': 'GRP Database ist ein inoffizieller Community-Hub, der GTA Roleplay einfacher und unterhaltsamer machen soll. Unser Ziel ist es, wertvolle Informationen an einem Ort zu sammeln — von Artikelwerten und Kleidungsoptionen bis hin zu Anfängertipps und Leitfäden — um Spielern zu helfen, schnell zu finden, was sie beim Spielen auf dem Server benötigen.',
    'welcome.disclaimer': 'GRP Database ist NICHT offiziell oder mit den Entwicklern des Spiels verbunden.',
    'admin.access': 'Admin-Zugang',
    'admin.panel': 'Admin-Panel',
    'admin.login': 'Admin-Anmeldung',
    'admin.description': 'Sie sind als Administrator angemeldet. Greifen Sie auf das Admin-Panel zu, um die Datenbank und Systemeinstellungen zu verwalten.',
    'admin.login_description': 'Sind Sie Administrator? Greifen Sie auf das Admin-Panel zu, um die Datenbank und Systemeinstellungen zu verwalten.',
    'values.title': 'Artikelwerte',
    'values.description': 'Finden Sie aktuelle Marktwerte für Fahrzeuge, Kleidung und Artikel.',
    'battlepass.title': 'Battlepass',
    'battlepass.description': 'Verfolgen Sie Ihren Battlepass-Fortschritt und Belohnungen.',
    'beginner.title': 'Anfängerhilfe',
    'beginner.description': 'Wesentliche Leitfäden für neue Spieler.',
    'bunker.title': 'Bunker-Hilfe',
    'bunker.description': 'Bunker-Management und Optimierungsleitfäden.',
    'events.title': 'Veranstaltungen',
    'events.description': 'Server-Events und Aktivitäten.',
    'lifeinvader.title': 'LifeInvader Vorlagen',
    'lifeinvader.description': 'Vorgefertigte Anzeigenvorlagen für LifeInvader.',
    'improvements.title': 'Verbesserungen',
    'improvements.description': 'Schlagen Sie Verbesserungen vor und melden Sie Bugs.',
    'suggestions.title': 'Vorschläge',
    'suggestions.description': 'Reichen Sie Ihre Vorschläge für die Datenbank ein.',
    'treasure.title': 'Schatzhelfer',
    'treasure.description': 'Finden Sie Schatzstandorte und Belohnungen.',
    'pet.title': 'Haustier-Timer',
    'pet.description': 'Verfolgen Sie Ihren Haustierfütterungsplan.',
    'ai.format_my_ad': 'Meine Anzeige formatieren',
    'ai.description': 'Verwenden Sie KI, um Ihre Anzeigen nach Richtlinien zu formatieren.',
    'community.title': 'Gemeinschaftsgetriebene Plattform',
    'community.built_by_players': '🤝 Von Spielern, für Spieler gebaut',
    'community.built_description': 'Diese Plattform wird von der GRP Database-Gemeinschaft gepflegt und aktualisiert. Alle Werte, Vorlagen und Funktionen werden von aktiven Spielern beigetragen, die die Marktdynamik und Gemeinschaftsbedürfnisse verstehen.',
    'community.real_time_data': '📊 Echtzeit-Marktdaten',
    'community.data_description': 'Erhalten Sie genaue, aktuelle Marktwerte für Fahrzeuge, Kleidung und Gegenstände. Unsere Gemeinschaft stellt sicher, dass die Daten die aktuellen Marktbedingungen widerspiegeln und Ihnen helfen, fundierte Handelsentscheidungen zu treffen.',
    'navigation.categories': 'Kategorien',
    'how_to_join': 'Wie beitreten?',
    'notification.new_update': 'Neues Update!',
    'notification.close': 'Popup schließen',
    'community.ai_powered': '🎯 KI-gestützte Unterstützung',
    'community.ai_description': 'Unser fortschrittlicher KI-Assistent lernt aus Community-Feedback, um bessere Anzeigenformatierung und Vorschläge zu bieten. Jede Korrektur hilft, das System für alle zu verbessern.',
    'community.continuous_improvement': '🔄 Kontinuierliche Verbesserung',
    'community.improvement_description': 'Die Plattform entwickelt sich basierend auf Community-Feedback und -Bedürfnissen. Neue Funktionen, Kategorien und Verbesserungen werden regelmäßig hinzugefügt, um Ihre Erfahrung zu verbessern.',
    'community.tip': '💡 Tipp:',
    'community.tip_text': 'Einen veralteten Wert gefunden oder einen Vorschlag? Kontaktieren Sie robthemaster auf Discord, um die Plattform für alle zu verbessern!',
    'categories.cars': 'Autos',
    'categories.boats': 'Boote',
    'categories.planes': 'Flugzeuge',
    'categories.helicopters': 'Hubschrauber',
    'categories.clothing_list': 'Kleidungsliste',
    'categories.masks': 'Masken',
    'categories.luminous_clothing': 'Leuchtende Kleidung',
    'categories.items': 'Gegenstände',
    'categories.motorcycles': 'Motorräder',
    'categories.illegal_items': 'Illegale Gegenstände',
    'categories.cropped_collection_shirts': 'Cropped Collection Hemden',
    'categories.denim_jackets': 'Denim Jacken',
    'navigation.home': 'Startseite',
    'navigation.logout': 'Abmelden',
    'page_titles.battlepass': 'Kampfpass',
    'page_titles.bunker_help': 'Bunker Hilfe',
    'page_titles.pet_timer': 'Haustier Timer',
    'page_titles.lifeinvader': 'LifeInvader',
    'page_titles.suggestions': 'Vorschläge',
    'page_titles.improvements': 'Verbesserungen',
    'page_titles.admin_panel': 'Admin Panel',
    'events.school.title': 'Schulveranstaltung',
    'events.school.description': 'Chemie-Farbmischer für Schulveranstaltungen.',
    'events.school.chemistry': 'Chemie',
    'footer.description': 'Bereitstellung von Informationen, Tools und Analysen für die GTA Roleplay-Handels-, Gaming- und verwandten Gemeinschaften.',
    'footer.grand_roleplay_trademark': 'Grand Roleplay und seine verschiedenen Marken und Logos sind Marken von Grand Roleplay.',
    'footer.gta_v_trademark': 'Grand Theft Auto V ist eine Marke von Take-Two Interactive Software Inc.',
    'footer.disclaimer': 'GRP Database wird nicht von GTA V und Grand Roleplay unterstützt, gesponsert oder ist mit ihnen verbunden.',
    'footer.privacy_policy': 'Datenschutzrichtlinie',
    'footer.contact': 'Kontakt',
    'privacy.title': 'Datenschutzrichtlinie',
    'privacy.data_collection.title': 'Datensammlung',
    'privacy.data_collection.description': 'GRP Database erfordert keine Benutzerkonten oder persönliche Informationen zur Nutzung der Website. Wir setzen keine Tracking-Cookies.',
    'privacy.data_collection.analytics': 'Wir verwenden datenschutzfreundliche Analysen (von Vercel) um zu verstehen, wie Besucher die Website nutzen. Dies kann anonymisierte Informationen umfassen wie:',
    'privacy.data_collection.browser_type': 'Browsertyp',
    'privacy.data_collection.pages_visited': 'Besuchte Seiten',
    'privacy.data_collection.approximate_location': 'Ungefährer Standort (basierend auf IP-Adresse)',
    'privacy.data_collection.ip_addresses': 'IP-Adressen werden nur zur Generierung von Nutzungsstatistiken verarbeitet und anonymisiert. Wir verwenden sie nicht zur persönlichen Identifizierung von Besuchern.',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.description': 'GRP Database verwendet keine Tracking-Cookies.',
    'privacy.data_sharing.title': 'Datenweitergabe',
    'privacy.data_sharing.description': 'Wir verkaufen, teilen oder geben Ihre Informationen nicht an Dritte weiter. Analysedaten werden nur zur Verbesserung der Website verwendet.',
    'privacy.contact.title': 'Kontakt',
    'privacy.contact.description': 'Wenn Sie Fragen zu dieser Datenschutzrichtlinie haben, wenden Sie sich bitte über das Kontaktformular oder Community-Kanäle.',
    'contact.title': 'Kontaktieren Sie uns',
    'contact.description': 'Haben Sie eine Frage oder einen Vorschlag? Wir würden gerne von Ihnen hören!',
    'contact.email_label': 'E-Mail-Adresse',
    'contact.email_placeholder': 'ihre.email@beispiel.com',
    'contact.subject_label': 'Betreff',
    'contact.subject_placeholder': 'Worum geht es?',
    'contact.message_label': 'Nachricht',
    'contact.message_placeholder': 'Teilen Sie uns mit, was Sie denken...',
    'contact.send_button': 'Nachricht senden',
    'contact.sending': 'Wird gesendet...',
    'contact.success_message': 'Vielen Dank! Ihre Nachricht wurde erfolgreich gesendet.',
    'contact.error_message': 'Entschuldigung, beim Senden Ihrer Nachricht ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
    'car_customizer.title': 'Auto-Konfigurator',
    'car_customizer.description': 'Konfigurieren Sie Ihr Traumauto mit realitätsnahen Modellen aus GTA V. Wählen Sie Farben, Teile und Zubehör, um Ihr perfektes Fahrzeug zu erstellen.',
    'car_customizer.select_car': 'Auto-Modell auswählen',
    'car_customizer.customize': 'Ihr Auto konfigurieren',
    'car_customizer.color': 'Farbe',
    'car_customizer.parts': 'Teile',
    'car_customizer.spoiler': 'Heckflügel',
    'car_customizer.neon': 'Neon-Lichter',
    'car_customizer.tint': 'Fenster-Tönung',
    'car_customizer.no_tint': 'Keine Tönung',
    'car_customizer.light_tint': 'Helle Tönung',
    'car_customizer.medium_tint': 'Mittlere Tönung',
    'car_customizer.dark_tint': 'Dunkle Tönung',
    'car_customizer.reset': 'Zurücksetzen',
    'car_customizer.save': 'Design speichern',
    'car_customizer.total_price': 'Gesamtpreis',
    'car_customizer.price_note': 'Preise basieren auf In-Game-Werten und können variieren',
    'car_customizer.privacy_notice_title': 'Datenschutzhinweis',
    'car_customizer.privacy_notice_text': 'Ihre Anpassungen werden lokal in Ihrem Browser gespeichert und nicht an unsere Server gesendet. Während der Anpassung werden keine persönlichen Daten gesammelt.',
    'car_customizer.preview': '3D-Vorschau',
    'car_customizer.custom_color': 'Benutzerdefinierte Farbe',
    'car_customizer.underglow': 'Unterbodenbeleuchtung',
  },
  rs: {
    'welcome.title': 'Добродошао у GRP Database',
    'welcome.description': 'GRP Database је незванични заједнички центар дизајниран да учини GTA Roleplay лакшим и пријатнијим. Наш циљ је да прикупимо вредне информације на једном месту — од вредности предмета и опција одеће до савета за почетнике и водича — помажући играчима да брзо пронађу оно што им треба док играју на серверу.',
    'welcome.disclaimer': 'GRP Database НИЈЕ званичан или повезан са програмерима игре.',
    'admin.access': 'Admin Приступ',
    'admin.panel': 'Admin Панел',
    'admin.login': 'Admin Пријава',
    'admin.description': 'Тренутно сте пријављени као администратор. Приступите admin панелу да управљате базом података и системским подешавањима.',
    'admin.login_description': 'Да ли сте администратор? Приступите admin панелу да управљате базом података и системским подешавањима.',
    'values.title': 'Вредности Предмета',
    'values.description': 'Пронађите тренутне тржишне вредности за возила, одећу и предмете.',
    'battlepass.title': 'Battlepass',
    'battlepass.description': 'Пратите свој battlepass напредак и награде.',
    'beginner.title': 'Помоћ за Почетнике',
    'beginner.description': 'Основни водичи за нове играче.',
    'bunker.title': 'Помоћ за Бункер',
    'bunker.description': 'Водичи за управљање бункером и оптимизацију.',
    'events.title': 'Догађаји',
    'events.description': 'Серверски догађаји и активности.',
    'lifeinvader.title': 'LifeInvader Шаблони',
    'lifeinvader.description': 'Унапред форматирани шаблони огласа за LifeInvader.',
    'improvements.title': 'Побољшања',
    'improvements.description': 'Предложите побољшања и пријавите грешке.',
    'suggestions.title': 'Предлози',
    'suggestions.description': 'Пошаљите своје предлоге за базу података.',
    'treasure.title': 'Помоћник за Благо',
    'treasure.description': 'Пронађите локације блага и награде.',
    'pet.title': 'Таймер за Љубимце',
    'pet.description': 'Пратите свој распоред храњења љубимаца.',
    'ai.format_my_ad': 'Форматирај мој оглас',
    'ai.description': 'Користите АИ да форматирате своје огласе према политици.',
    'community.title': 'Заједничка Платформа',
    'community.built_by_players': '🤝 Направљено од стране играча, за играче',
    'community.built_description': 'Ову платформу одржава и ажурира GRP Database заједница. Све вредности, шаблони и функције доприносе активни играчи који разумеју тржишну динамику и потребе заједнице.',
    'community.real_time_data': '📊 Подаци о тржишту у реалном времену',
    'community.data_description': 'Добијте тачне, ажуриране тржишне вредности за возила, одећу и предмете. Наша заједница обезбеђује да подаци одражавају тренутне тржишне услове и помажу вам да доносите информисане трговинске одлуке.',
    'navigation.categories': 'Категорије',
    'how_to_join': 'Како се придружити?',
    'notification.new_update': 'Ново Ажурирање!',
    'notification.close': 'Затвори popup',
    'community.ai_powered': '🎯 АИ-Помоћ',
    'community.ai_description': 'Наш напредни АИ асистент учи из повратних информација заједнице да пружи боје форматирање огласа и предлоге. Свака корекција помаже побољшању система за све.',
    'community.continuous_improvement': '🔄 Континуирано Побољшање',
    'community.improvement_description': 'Платформа се развија на основу повратних информација и потреба заједнице. Нове функције, категорије и побољшања се редовно додају да побољшају ваше искуство.',
    'community.tip': '💡 Савет:',
    'community.tip_text': 'Пронашли сте застарелу вредност или имате предлог? Контактирајте robthemaster на дискорду да помогнете побољшању платформе за све!',
    'categories.cars': 'Аутомобили',
    'categories.boats': 'Бродови',
    'categories.planes': 'Авиони',
    'categories.helicopters': 'Хеликоптери',
    'categories.clothing_list': 'Листа Одеће',
    'categories.masks': 'Маске',
    'categories.luminous_clothing': 'Светлећа Одећа',
    'categories.items': 'Предмети',
    'categories.motorcycles': 'Мотоцикли',
    'categories.illegal_items': 'Илегални Предмети',
    'categories.cropped_collection_shirts': 'Cropped Collection Мајице',
    'categories.denim_jackets': 'Деним Јакне',
    'navigation.home': 'Почетна',
    'navigation.logout': 'Одјава',
    'page_titles.battlepass': 'Батлпас',
    'page_titles.bunker_help': 'Бункер Помоћ',
    'page_titles.pet_timer': 'Таймер Питомца',
    'page_titles.lifeinvader': 'LifeInvader',
    'page_titles.suggestions': 'Предлози',
    'page_titles.improvements': 'Побољшања',
    'page_titles.admin_panel': 'Админ Панел',
    'events.school.title': 'Школски Догађај',
    'events.school.description': 'Хемијски мешач боја за школске догађаје.',
    'events.school.chemistry': 'Хемија',
    'footer.description': 'Пружање информација, алата и аналитика за GTA Roleplay трговину, гејминг и сродне заједнице.',
    'footer.grand_roleplay_trademark': 'Grand Roleplay и његове разне марке и логоти су заштитни знакови Grand Roleplay-а.',
    'footer.gta_v_trademark': 'Grand Theft Auto V је заштитни знак Take-Two Interactive Software Inc.',
    'footer.disclaimer': 'GRP Database није одобрен, спонзорисан или повезан са GTA V и Grand Roleplay.',
    'footer.privacy_policy': 'Политика приватности',
    'footer.contact': 'Контакт',
    'privacy.title': 'Политика приватности',
    'privacy.data_collection.title': 'Прикупљање података',
    'privacy.data_collection.description': 'GRP Database не захтева корисничке налоге или личне информације за коришћење веб-сајта. Не постављамо пратеће колачиће.',
    'privacy.data_collection.analytics': 'Користимо аналитику пријатељску према приватности (од Vercel-а) да бисмо разумели како посетиоци користе сајт. Ово може укључивати анонимне информације као што су:',
    'privacy.data_collection.browser_type': 'Тип прегледача',
    'privacy.data_collection.pages_visited': 'Посећене странице',
    'privacy.data_collection.approximate_location': 'Приближна локација (на основу IP адресе)',
    'privacy.data_collection.ip_addresses': 'IP адресе се обрађују само за генерисање статистика коришћења и анонимизују се. Не користимо их за лично идентификовање посетилаца.',
    'privacy.cookies.title': 'Колачићи',
    'privacy.cookies.description': 'GRP Database не користи пратеће колачиће.',
    'privacy.data_sharing.title': 'Дељење података',
    'privacy.data_sharing.description': 'Не продајемо, не делимо или не откривамо ваше информације трећим странама. Аналитички подаци се користе само за побољшање веб-сајта.',
    'privacy.contact.title': 'Контакт',
    'privacy.contact.description': 'Ако имате питања о овој Полици приватности, молимо обратите се преко контакт форме или заједничких канала.',
    'contact.title': 'Контактирајте нас',
    'contact.description': 'Имате питање или предлог? Волели бисмо да чујемо од вас!',
    'contact.email_label': 'Е-маил адреса',
    'contact.email_placeholder': 'vas.email@primer.com',
    'contact.subject_label': 'Предмет',
    'contact.subject_placeholder': 'О чему се ради?',
    'contact.message_label': 'Порука',
    'contact.message_placeholder': 'Реците нам шта мислите...',
    'contact.send_button': 'Пошаљи поруку',
    'contact.sending': 'Шаље се...',
    'contact.success_message': 'Хвала вам! Ваша порука је успешно послата.',
    'contact.error_message': 'Извините, дошло је до грешке при слању ваше поруке. Молимо покушајте поново.',
    'car_customizer.title': 'Конфигуратор аутомобила',
    'car_customizer.description': 'Прилагодите свој сан аутомобил са моделима инспирисаним стварним животом из GTA V. Изаберите боје, делове и додатке да направите свој савршен воз.',
    'car_customizer.select_car': 'Изаберите модел аутомобила',
    'car_customizer.customize': 'Прилагодите свој аутомобил',
    'car_customizer.color': 'Боја',
    'car_customizer.parts': 'Делови',
    'car_customizer.spoiler': 'Спојлер',
    'car_customizer.neon': 'Неон светла',
    'car_customizer.tint': 'Затамњење стакла',
    'car_customizer.no_tint': 'Без затамњења',
    'car_customizer.light_tint': 'Светло затамњење',
    'car_customizer.medium_tint': 'Средње затамњење',
    'car_customizer.dark_tint': 'Тамно затамњење',
    'car_customizer.reset': 'Ресетуј',
    'car_customizer.save': 'Сачувај дизајн',
    'car_customizer.total_price': 'Укупна цена',
    'car_customizer.price_note': 'Цене се заснивају на вредностима у игри и могу варирати',
    'car_customizer.privacy_notice_title': 'Обавештење о приватности',
    'car_customizer.privacy_notice_text': 'Ваше прилагођавања се чувају локално у вашем прегледачу и не шаљу се на наше сервере. Током прилагођавања не прикупљају се лични подаци.',
    'car_customizer.preview': '3D Преглед',
    'car_customizer.custom_color': 'Прилагођена Боја',
    'car_customizer.underglow': 'Подсветка',
  },
  it: {
    'welcome.title': 'Benvenuto in GRP Database',
    'welcome.description': 'GRP Database è un hub comunitario non ufficiale progettato per rendere GTA Roleplay più facile e divertente. Il nostro obiettivo è raccogliere informazioni preziose in un unico posto — dai valori degli oggetti alle opzioni di abbigliamento, dai consigli per principianti alle guide — aiutando i giocatori a trovare rapidamente ciò di cui hanno bisogno mentre giocano sul server.',
    'welcome.disclaimer': 'GRP Database NON è ufficiale o affiliato agli sviluppatori del gioco.',
    'admin.access': 'Accesso Admin',
    'admin.panel': 'Pannello Admin',
    'admin.login': 'Login Admin',
    'admin.description': 'Sei attualmente connesso come amministratore. Accedi al pannello admin per gestire il database e le impostazioni di sistema.',
    'admin.login_description': 'Sei un amministratore? Accedi al pannello admin per gestire il database e le impostazioni di sistema.',
    'values.title': 'Valori Oggetti',
    'values.description': 'Trova i valori di mercato attuali per veicoli, abbigliamento e oggetti.',
    'battlepass.title': 'Battlepass',
    'battlepass.description': 'Traccia i tuoi progressi e ricompense del battlepass.',
    'beginner.title': 'Aiuto Principianti',
    'beginner.description': 'Guide essenziali per nuovi giocatori.',
    'bunker.title': 'Aiuto Bunker',
    'bunker.description': 'Guide per la gestione e ottimizzazione del bunker.',
    'events.title': 'Eventi',
    'events.description': 'Eventi e attività del server.',
    'lifeinvader.title': 'Modelli LifeInvader',
    'lifeinvader.description': 'Modelli di annunci pre-formattati per LifeInvader.',
    'improvements.title': 'Miglioramenti',
    'improvements.description': 'Suggerisci miglioramenti e segnala bug.',
    'suggestions.title': 'Suggerimenti',
    'suggestions.description': 'Invia i tuoi suggerimenti per il database.',
    'treasure.title': 'Helper Tesoro',
    'treasure.description': 'Trova le posizioni dei tesori e le ricompense.',
    'pet.title': 'Timer Animale',
    'pet.description': 'Traccia il tuo programma di alimentazione degli animali.',
    'ai.format_my_ad': 'Formatta il mio annuncio',
    'ai.description': 'Usa l\'AI per formattare i tuoi annunci secondo le politiche.',
    'community.title': 'Piattaforma Guidata dalla Comunità',
    'community.built_by_players': '🤝 Costruito dai Giocatori, per i Giocatori',
    'community.built_description': 'Questa piattaforma è mantenuta e aggiornata dalla comunità GRP Database. Tutti i valori, modelli e funzionalità sono contribuiti da giocatori attivi che comprendono le dinamiche di mercato e le esigenze della comunità.',
    'community.real_time_data': '📊 Dati di Mercato in Tempo Reale',
    'community.data_description': 'Ottieni valori di mercato accurati e aggiornati per veicoli, abbigliamento e oggetti. La nostra comunità garantisce che i dati riflettano le condizioni di mercato attuali e ti aiutino a prendere decisioni commerciali informate.',
    'navigation.categories': 'Categorie',
    'how_to_join': 'Come partecipare?',
    'notification.new_update': 'Nuovo Aggiornamento!',
    'notification.close': 'Chiudi popup',
    'community.ai_powered': '🎯 Assistenza Basata su IA',
    'community.ai_description': 'Il nostro assistente IA avanzato impara dal feedback della comunità per fornire una migliore formattazione degli annunci e suggerimenti. Ogni correzione aiuta a migliorare il sistema per tutti.',
    'community.continuous_improvement': '🔄 Miglioramento Continuo',
    'community.improvement_description': 'La piattaforma si evolve in base al feedback e alle esigenze della comunità. Nuove funzionalità, categorie e miglioramenti vengono regolarmente aggiunti per migliorare la tua esperienza.',
    'community.tip': '💡 Suggerimento:',
    'community.tip_text': 'Trovato un valore obsoleto o hai un suggerimento? Contatta robthemaster su discord per aiutare a migliorare la piattaforma per tutti!',
    'categories.cars': 'Auto',
    'categories.boats': 'Barche',
    'categories.planes': 'Aerei',
    'categories.helicopters': 'Elicotteri',
    'categories.clothing_list': 'Lista Abbigliamento',
    'categories.masks': 'Maschere',
    'categories.luminous_clothing': 'Abbigliamento Luminoso',
    'categories.items': 'Oggetti',
    'categories.motorcycles': 'Moto',
    'categories.illegal_items': 'Oggetti Illegali',
    'categories.cropped_collection_shirts': 'Magliette Cropped Collection',
    'categories.denim_jackets': 'Giacche Denim',
    'navigation.home': 'Home',
    'navigation.logout': 'Disconnetti',
    'page_titles.battlepass': 'Battlepass',
    'page_titles.bunker_help': 'Aiuto Bunker',
    'page_titles.pet_timer': 'Timer Animale',
    'page_titles.lifeinvader': 'LifeInvader',
    'page_titles.suggestions': 'Suggerimenti',
    'page_titles.improvements': 'Miglioramenti',
    'page_titles.admin_panel': 'Pannello Admin',
    'events.school.title': 'Evento Scolastico',
    'events.school.description': 'Mescolatore di colori chimici per eventi scolastici.',
    'events.school.chemistry': 'Chimica',
    'footer.description': 'Fornire informazioni, strumenti e analisi per le comunità di trading, gaming e correlate di GTA Roleplay.',
    'footer.grand_roleplay_trademark': 'Grand Roleplay e i suoi vari marchi e loghi sono marchi di Grand Roleplay.',
    'footer.gta_v_trademark': 'Grand Theft Auto V è un marchio di Take-Two Interactive Software Inc.',
    'footer.disclaimer': 'GRP Database non è approvato, sponsorizzato o affiliato con GTA V e Grand Roleplay.',
    'footer.privacy_policy': 'Informativa sulla Privacy',
    'footer.contact': 'Contatto',
    'privacy.title': 'Informativa sulla Privacy',
    'privacy.data_collection.title': 'Raccolta Dati',
    'privacy.data_collection.description': 'GRP Database non richiede account utente o informazioni personali per utilizzare il sito web. Non impostiamo cookie di tracciamento.',
    'privacy.data_collection.analytics': 'Utilizziamo analisi rispettose della privacy (fornite da Vercel) per capire come i visitatori utilizzano il sito. Questo può includere informazioni anonimizzate come:',
    'privacy.data_collection.browser_type': 'Tipo di browser',
    'privacy.data_collection.pages_visited': 'Pagine visitate',
    'privacy.data_collection.approximate_location': 'Posizione approssimativa (basata sull\'indirizzo IP)',
    'privacy.data_collection.ip_addresses': 'Gli indirizzi IP vengono elaborati solo per generare statistiche di utilizzo e sono anonimizzati. Non li utilizziamo per identificare personalmente i visitatori.',
    'privacy.cookies.title': 'Cookie',
    'privacy.cookies.description': 'GRP Database non utilizza cookie di tracciamento.',
    'privacy.data_sharing.title': 'Condivisione Dati',
    'privacy.data_sharing.description': 'Non vendiamo, condividiamo o divulghiamo le tue informazioni a terze parti. I dati analitici vengono utilizzati solo per migliorare il sito web.',
    'privacy.contact.title': 'Contatto',
    'privacy.contact.description': 'Se hai domande su questa Informativa sulla Privacy, contattaci tramite il modulo di contatto o i canali della comunità.',
    'contact.title': 'Contattaci',
    'contact.description': 'Hai una domanda o un suggerimento? Ci piacerebbe sentirti!',
    'contact.email_label': 'Indirizzo Email',
    'contact.email_placeholder': 'tua.email@esempio.com',
    'contact.subject_label': 'Oggetto',
    'contact.subject_placeholder': 'Di cosa si tratta?',
    'contact.message_label': 'Messaggio',
    'contact.message_placeholder': 'Dicci cosa pensi...',
    'contact.send_button': 'Invia Messaggio',
    'contact.sending': 'Invio in corso...',
    'contact.success_message': 'Grazie! Il tuo messaggio è stato inviato con successo.',
    'contact.error_message': 'Spiacenti, si è verificato un errore durante l\'invio del messaggio. Riprova.',
    'car_customizer.title': 'Configuratore Auto',
    'car_customizer.description': 'Personalizza la tua auto dei sogni con modelli ispirati alla vita reale da GTA V. Scegli colori, parti e accessori per creare la tua vettura perfetta.',
    'car_customizer.select_car': 'Seleziona Modello Auto',
    'car_customizer.customize': 'Personalizza la Tua Auto',
    'car_customizer.color': 'Colore',
    'car_customizer.parts': 'Parti',
    'car_customizer.spoiler': 'Spoiler',
    'car_customizer.neon': 'Luci Neon',
    'car_customizer.tint': 'Tintura Vetri',
    'car_customizer.no_tint': 'Nessuna Tintura',
    'car_customizer.light_tint': 'Tintura Leggera',
    'car_customizer.medium_tint': 'Tintura Media',
    'car_customizer.dark_tint': 'Tintura Scura',
    'car_customizer.reset': 'Ripristina',
    'car_customizer.save': 'Salva Design',
    'car_customizer.total_price': 'Prezzo Totale',
    'car_customizer.price_note': 'I prezzi si basano sui valori in-game e possono variare',
    'car_customizer.privacy_notice_title': 'Avviso Privacy',
    'car_customizer.privacy_notice_text': 'Le tue personalizzazioni sono memorizzate localmente nel tuo browser e non vengono inviate ai nostri server. Durante la personalizzazione non vengono raccolti dati personali.',
    'car_customizer.preview': 'Anteprima 3D',
    'car_customizer.custom_color': 'Colore Personalizzato',
    'car_customizer.underglow': 'Illuminazione Sottoscocca',
  },
  fr: {
    'welcome.title': 'Bienvenue sur GRP Database',
    'welcome.description': 'GRP Database est un hub communautaire non officiel conçu pour rendre GTA Roleplay plus facile et plus agréable. Notre objectif est de rassembler des informations précieuses en un seul endroit — des valeurs d\'articles aux options de vêtements, des conseils pour débutants aux guides — aidant les joueurs à trouver rapidement ce dont ils ont besoin en jouant sur le serveur.',
    'welcome.disclaimer': 'GRP Database N\'EST PAS officiel ou affilié aux développeurs du jeu.',
    'admin.access': 'Accès Admin',
    'admin.panel': 'Panneau Admin',
    'admin.login': 'Connexion Admin',
    'admin.description': 'Vous êtes actuellement connecté en tant qu\'administrateur. Accédez au panneau admin pour gérer la base de données et les paramètres système.',
    'admin.login_description': 'Êtes-vous administrateur? Accédez au panneau admin pour gérer la base de données et les paramètres système.',
    'values.title': 'Valeurs Objets',
    'values.description': 'Trouvez les valeurs de marché actuelles pour les véhicules, vêtements et objets.',
    'battlepass.title': 'Battlepass',
    'battlepass.description': 'Suivez vos progrès et récompenses du battlepass.',
    'beginner.title': 'Aide Débutant',
    'beginner.description': 'Guides essentiels pour les nouveaux joueurs.',
    'bunker.title': 'Aide Bunker',
    'bunker.description': 'Guides de gestion et d\'optimisation du bunker.',
    'events.title': 'Événements',
    'events.description': 'Événements et activités du serveur.',
    'lifeinvader.title': 'Modèles LifeInvader',
    'lifeinvader.description': 'Modèles d\'annonces pré-formatés pour LifeInvader.',
    'improvements.title': 'Améliorations',
    'improvements.description': 'Suggérez des améliorations et signalez des bugs.',
    'suggestions.title': 'Suggestions',
    'suggestions.description': 'Soumettez vos suggestions pour la base de données.',
    'treasure.title': 'Helper Trésor',
    'treasure.description': 'Trouvez les emplacements de trésors et récompenses.',
    'pet.title': 'Minuteur Animal',
    'pet.description': 'Suivez votre planning d\'alimentation des animaux.',
    'ai.format_my_ad': 'Formater mon annonce',
    'ai.description': 'Utilisez l\'IA pour formater vos annonces selon les politiques.',
    'community.title': 'Plateforme Communautaire',
    'community.built_by_players': '🤝 Construit par les Joueurs, pour les Joueurs',
    'community.built_description': 'Cette plateforme est maintenue et mise à jour par la communauté GRP Database. Toutes les valeurs, modèles et fonctionnalités sont contribuées par des joueurs actifs qui comprennent les dynamiques du marché et les besoins de la communauté.',
    'community.real_time_data': '📊 Données de Marché en Temps Réel',
    'community.data_description': 'Obtenez des valeurs de marché précises et à jour pour les véhicules, vêtements et objets. Notre communauté garantit que les données reflètent les conditions de marché actuelles et vous aident à prendre des décisions commerciales éclairées.',
    'navigation.categories': 'Catégories',
    'how_to_join': 'Comment rejoindre?',
    'notification.new_update': 'Nouvelle Mise à Jour!',
    'notification.close': 'Fermer popup',
    'community.ai_powered': '🎯 Assistance Basée sur l\'IA',
    'community.ai_description': 'Notre assistant IA avancé apprend des commentaires de la communauté pour fournir une meilleure mise en forme des annonces et des suggestions. Chaque correction aide à améliorer le système pour tous.',
    'community.continuous_improvement': '🔄 Amélioration Continue',
    'community.improvement_description': 'La plateforme évolue en fonction des commentaires et des besoins de la communauté. De nouvelles fonctionnalités, catégories et améliorations sont régulièrement ajoutées pour améliorer votre expérience.',
    'community.tip': '💡 Conseil:',
    'community.tip_text': 'Trouvé une valeur obsolète ou avez une suggestion? Contactez robthemaster sur discord pour aider à améliorer la plateforme pour tous!',
    'categories.cars': 'Voitures',
    'categories.boats': 'Bateaux',
    'categories.planes': 'Avions',
    'categories.helicopters': 'Hélicoptères',
    'categories.clothing_list': 'Liste de Vêtements',
    'categories.masks': 'Masques',
    'categories.luminous_clothing': 'Vêtements Lumineux',
    'categories.items': 'Objets',
    'categories.motorcycles': 'Motos',
    'categories.illegal_items': 'Objets Illégaux',
    'categories.cropped_collection_shirts': 'T-shirts Cropped Collection',
    'categories.denim_jackets': 'Vestes Denim',
    'navigation.home': 'Accueil',
    'navigation.logout': 'Déconnexion',
    'page_titles.battlepass': 'Passe de Combat',
    'page_titles.bunker_help': 'Aide Bunker',
    'page_titles.pet_timer': 'Minuteur Animal',
    'page_titles.lifeinvader': 'LifeInvader',
    'page_titles.suggestions': 'Suggestions',
    'page_titles.improvements': 'Améliorations',
    'page_titles.admin_panel': 'Panneau Admin',
    'events.school.title': 'Événement Scolaire',
    'events.school.description': 'Mélangeur de couleurs chimiques pour événements scolaires.',
    'events.school.chemistry': 'Chimie',
    'footer.description': 'Fournir des informations, des outils et des analyses pour les communautés de trading, de gaming et connexes de GTA Roleplay.',
    'footer.grand_roleplay_trademark': 'Grand Roleplay et ses diverses marques et logos sont des marques de Grand Roleplay.',
    'footer.gta_v_trademark': 'Grand Theft Auto V est une marque de Take-Two Interactive Software Inc.',
    'footer.disclaimer': 'GRP Database n\'est pas approuvé, sponsorisé ou affilié à GTA V et Grand Roleplay.',
    'footer.privacy_policy': 'Politique de Confidentialité',
    'footer.contact': 'Contact',
    'privacy.title': 'Politique de Confidentialité',
    'privacy.data_collection.title': 'Collecte de Données',
    'privacy.data_collection.description': 'GRP Database ne nécessite pas de comptes utilisateur ou d\'informations personnelles pour utiliser le site web. Nous ne définissons aucun cookie de suivi.',
    'privacy.data_collection.analytics': 'Nous utilisons des analyses respectueuses de la vie privée (alimentées par Vercel) pour comprendre comment les visiteurs utilisent le site. Cela peut inclure des informations anonymisées telles que:',
    'privacy.data_collection.browser_type': 'Type de navigateur',
    'privacy.data_collection.pages_visited': 'Pages visitées',
    'privacy.data_collection.approximate_location': 'Localisation approximative (basée sur l\'adresse IP)',
    'privacy.data_collection.ip_addresses': 'Les adresses IP sont traitées uniquement pour générer des statistiques d\'utilisation et sont anonymisées. Nous ne les utilisons pas pour identifier personnellement les visiteurs.',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.description': 'GRP Database n\'utilise pas de cookies de suivi.',
    'privacy.data_sharing.title': 'Partage de Données',
    'privacy.data_sharing.description': 'Nous ne vendons, ne partageons ni ne divulguons pas vos informations à des tiers. Les données analytiques ne sont utilisées que pour améliorer le site web.',
    'privacy.contact.title': 'Contact',
    'privacy.contact.description': 'Si vous avez des questions sur cette Politique de Confidentialité, veuillez nous contacter via le formulaire de contact ou les canaux communautaires.',
    'contact.title': 'Nous Contacter',
    'contact.description': 'Vous avez une question ou une suggestion? Nous aimerions vous entendre!',
    'contact.email_label': 'Adresse Email',
    'contact.email_placeholder': 'votre.email@exemple.com',
    'contact.subject_label': 'Sujet',
    'contact.subject_placeholder': 'De quoi s\'agit-il?',
    'contact.message_label': 'Message',
    'contact.message_placeholder': 'Dites-nous ce que vous pensez...',
    'contact.send_button': 'Envoyer le Message',
    'contact.sending': 'Envoi en cours...',
    'contact.success_message': 'Merci! Votre message a été envoyé avec succès.',
    'contact.error_message': 'Désolé, une erreur s\'est produite lors de l\'envoi de votre message. Veuillez réessayer.',
    'car_customizer.title': 'Configurateur de Voiture',
    'car_customizer.description': 'Personnalisez votre voiture de rêve avec des modèles inspirés de la vraie vie de GTA V. Choisissez couleurs, pièces et accessoires pour créer votre véhicule parfait.',
    'car_customizer.select_car': 'Sélectionner Modèle de Voiture',
    'car_customizer.customize': 'Personnaliser Votre Voiture',
    'car_customizer.color': 'Couleur',
    'car_customizer.parts': 'Pièces',
    'car_customizer.spoiler': 'Spoiler',
    'car_customizer.neon': 'Lumières Néon',
    'car_customizer.tint': 'Teinte Vitres',
    'car_customizer.no_tint': 'Aucune Teinte',
    'car_customizer.light_tint': 'Teinte Claire',
    'car_customizer.medium_tint': 'Teinte Moyenne',
    'car_customizer.dark_tint': 'Teinte Sombre',
    'car_customizer.reset': 'Réinitialiser',
    'car_customizer.save': 'Sauvegarder Design',
    'car_customizer.total_price': 'Prix Total',
    'car_customizer.price_note': 'Les prix sont basés sur les valeurs en jeu et peuvent varier',
    'car_customizer.privacy_notice_title': 'Avis de Confidentialité',
    'car_customizer.privacy_notice_text': 'Vos personnalisations sont stockées localement dans votre navigateur et ne sont pas envoyées à nos serveurs. Aucune donnée personnelle n\'est collectée lors de la personnalisation.',
    'car_customizer.preview': 'Aperçu 3D',
    'car_customizer.custom_color': 'Couleur Personnalisée',
    'car_customizer.underglow': 'Éclairage Sous Châssis',
  },
  es: {
    'welcome.title': 'Bienvenido a GRP Database',
    'welcome.description': 'GRP Database es un centro comunitario no oficial diseñado para hacer GTA Roleplay más fácil y agradable. Nuestro objetivo es recopilar información valiosa en un solo lugar — desde valores de artículos y opciones de ropa hasta consejos para principiantes y guías — ayudando a los jugadores a encontrar rápidamente lo que necesitan mientras juegan en el servidor.',
    'welcome.disclaimer': 'GRP Database NO es oficial o afiliado a los desarrolladores del juego.',
    'admin.access': 'Acceso Admin',
    'admin.panel': 'Panel Admin',
    'admin.login': 'Inicio de Sesión Admin',
    'admin.description': 'Actualmente estás conectado como administrador. Accede al panel admin para gestionar la base de datos y configuraciones del sistema.',
    'admin.login_description': '¿Eres administrador? Accede al panel admin para gestionar la base de datos y configuraciones del sistema.',
    'values.title': 'Valores de Artículos',
    'values.description': 'Encuentra los valores de mercado actuales para vehículos, ropa y artículos.',
    'battlepass.title': 'Battlepass',
    'battlepass.description': 'Rastrea tu progreso y recompensas del battlepass.',
    'beginner.title': 'Ayuda para Principiantes',
    'beginner.description': 'Guías esenciales para nuevos jugadores.',
    'bunker.title': 'Ayuda Bunker',
    'bunker.description': 'Guías de gestión y optimización del bunker.',
    'events.title': 'Eventos',
    'events.description': 'Eventos y actividades del servidor.',
    'lifeinvader.title': 'Plantillas LifeInvader',
    'lifeinvader.description': 'Plantillas de anuncios pre-formateadas para LifeInvader.',
    'improvements.title': 'Mejoras',
    'improvements.description': 'Sugiere mejoras y reporta errores.',
    'suggestions.title': 'Sugerencias',
    'suggestions.description': 'Envía tus sugerencias para la base de datos.',
    'treasure.title': 'Helper Tesoro',
    'treasure.description': 'Encuentra ubicaciones de tesoros y recompensas.',
    'pet.title': 'Timer Mascota',
    'pet.description': 'Rastrea tu horario de alimentación de mascotas.',
    'ai.format_my_ad': 'Formatear mi anuncio',
    'ai.description': 'Usa IA para formatear tus anuncios según las políticas.',
    'community.title': 'Plataforma Impulsada por la Comunidad',
    'community.built_by_players': '🤝 Construido por Jugadores, para Jugadores',
    'community.built_description': 'Esta plataforma es mantenida y actualizada por la comunidad GRP Database. Todos los valores, plantillas y características son contribuidos por jugadores activos que entienden las dinámicas del mercado y las necesidades de la comunidad.',
    'community.real_time_data': '📊 Datos de Mercado en Tiempo Real',
    'community.data_description': 'Obtén valores de mercado precisos y actualizados para vehículos, ropa y artículos. Nuestra comunidad asegura que los datos reflejen las condiciones actuales del mercado y te ayuden a tomar decisiones comerciales informadas.',
    'navigation.categories': 'Categorías',
    'how_to_join': '¿Cómo unirse?',
    'notification.new_update': '¡Nueva Actualización!',
    'notification.close': 'Cerrar popup',
    'community.ai_powered': '🎯 Asistencia Impulsada por IA',
    'community.ai_description': 'Nuestro asistente de IA avanzado aprende de los comentarios de la comunidad para proporcionar mejor formato de anuncios y sugerencias. Cada corrección ayuda a mejorar el sistema para todos.',
    'community.continuous_improvement': '🔄 Mejora Continua',
    'community.improvement_description': 'La plataforma evoluciona basándose en los comentarios y necesidades de la comunidad. Nuevas características, categorías y mejoras se agregan regularmente para mejorar tu experiencia.',
    'community.tip': '💡 Consejo:',
    'community.tip_text': '¿Encontraste un valor desactualizado o tienes una sugerencia? ¡Contacta a robthemaster en discord para ayudar a mejorar la plataforma para todos!',
    'categories.cars': 'Autos',
    'categories.boats': 'Barcos',
    'categories.planes': 'Aviones',
    'categories.helicopters': 'Helicópteros',
    'categories.clothing_list': 'Lista de Ropa',
    'categories.masks': 'Máscaras',
    'categories.luminous_clothing': 'Ropa Luminosa',
    'categories.items': 'Artículos',
    'categories.motorcycles': 'Motocicletas',
    'categories.illegal_items': 'Artículos Ilegales',
    'categories.cropped_collection_shirts': 'Camisetas Cropped Collection',
    'categories.denim_jackets': 'Chaquetas Denim',
    'navigation.home': 'Inicio',
    'navigation.logout': 'Cerrar Sesión',
    'page_titles.battlepass': 'Pase de Batalla',
    'page_titles.bunker_help': 'Ayuda Bunker',
    'page_titles.pet_timer': 'Temporizador Mascota',
    'page_titles.lifeinvader': 'LifeInvader',
    'page_titles.suggestions': 'Sugerencias',
    'page_titles.improvements': 'Mejoras',
    'page_titles.admin_panel': 'Panel Admin',
    'events.school.title': 'Evento Escolar',
    'events.school.description': 'Mezclador de colores químicos para eventos escolares.',
    'events.school.chemistry': 'Química',
    'footer.description': 'Proporcionando información, herramientas y análisis para las comunidades de trading, gaming y relacionadas de GTA Roleplay.',
    'footer.grand_roleplay_trademark': 'Grand Roleplay y sus varias marcas y logos son marcas registradas de Grand Roleplay.',
    'footer.gta_v_trademark': 'Grand Theft Auto V es una marca registrada de Take-Two Interactive Software Inc.',
    'footer.disclaimer': 'GRP Database no está respaldado, patrocinado o afiliado con GTA V y Grand Roleplay.',
    'footer.privacy_policy': 'Política de Privacidad',
    'footer.contact': 'Contacto',
    'privacy.title': 'Política de Privacidad',
    'privacy.data_collection.title': 'Recopilación de Datos',
    'privacy.data_collection.description': 'GRP Database no requiere cuentas de usuario o información personal para usar el sitio web. No establecemos cookies de seguimiento.',
    'privacy.data_collection.analytics': 'Utilizamos análisis respetuosos con la privacidad (potenciados por Vercel) para entender cómo los visitantes usan el sitio. Esto puede incluir información anonimizada como:',
    'privacy.data_collection.browser_type': 'Tipo de navegador',
    'privacy.data_collection.pages_visited': 'Páginas visitadas',
    'privacy.data_collection.approximate_location': 'Ubicación aproximada (basada en la dirección IP)',
    'privacy.data_collection.ip_addresses': 'Las direcciones IP se procesan solo para generar estadísticas de uso y se anonimizan. No las usamos para identificar personalmente a los visitantes.',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.description': 'GRP Database no utiliza cookies de seguimiento.',
    'privacy.data_sharing.title': 'Compartir Datos',
    'privacy.data_sharing.description': 'No vendemos, compartimos o divulgamos su información a terceros. Los datos analíticos solo se usan para mejorar el sitio web.',
    'privacy.contact.title': 'Contacto',
    'privacy.contact.description': 'Si tiene preguntas sobre esta Política de Privacidad, póngase en contacto a través del formulario de contacto o canales comunitarios.',
    'contact.title': 'Contáctanos',
    'contact.description': '¿Tienes una pregunta o sugerencia? ¡Nos encantaría escucharte!',
    'contact.email_label': 'Dirección de Email',
    'contact.email_placeholder': 'tu.email@ejemplo.com',
    'contact.subject_label': 'Asunto',
    'contact.subject_placeholder': '¿De qué se trata?',
    'contact.message_label': 'Mensaje',
    'contact.message_placeholder': 'Dinos qué piensas...',
    'contact.send_button': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.success_message': '¡Gracias! Tu mensaje ha sido enviado exitosamente.',
    'contact.error_message': 'Lo siento, hubo un error al enviar tu mensaje. Por favor, inténtalo de nuevo.',
    'car_customizer.title': 'Configurador de Autos',
    'car_customizer.description': 'Personaliza tu auto de ensueño con modelos inspirados en la vida real de GTA V. Elige colores, partes y accesorios para crear tu vehículo perfecto.',
    'car_customizer.select_car': 'Seleccionar Modelo de Auto',
    'car_customizer.customize': 'Personalizar Tu Auto',
    'car_customizer.color': 'Color',
    'car_customizer.parts': 'Partes',
    'car_customizer.spoiler': 'Spoiler',
    'car_customizer.neon': 'Luces Neón',
    'car_customizer.tint': 'Tinte de Ventanas',
    'car_customizer.no_tint': 'Sin Tinte',
    'car_customizer.light_tint': 'Tinte Claro',
    'car_customizer.medium_tint': 'Tinte Medio',
    'car_customizer.dark_tint': 'Tinte Oscuro',
    'car_customizer.reset': 'Reiniciar',
    'car_customizer.save': 'Guardar Diseño',
    'car_customizer.total_price': 'Precio Total',
    'car_customizer.price_note': 'Los precios se basan en valores del juego y pueden variar',
    'car_customizer.privacy_notice_title': 'Aviso de Privacidad',
    'car_customizer.privacy_notice_text': 'Tus personalizaciones se almacenan localmente en tu navegador y no se envían a nuestros servidores. No se recopilan datos personales durante la personalización.',
    'car_customizer.preview': 'Vista Previa 3D',
    'car_customizer.custom_color': 'Color Personalizado',
    'car_customizer.underglow': 'Iluminación Inferior',
  },
  pt: {
    'welcome.title': 'Bem-vindo ao GRP Database',
    'welcome.description': 'GRP Database é um centro comunitário não oficial projetado para tornar GTA Roleplay mais fácil e agradável. Nosso objetivo é reunir informações valiosas em um só lugar — desde valores de itens e opções de roupas até dicas para iniciantes e guias — ajudando os jogadores a encontrar rapidamente o que precisam enquanto jogam no servidor.',
    'welcome.disclaimer': 'GRP Database NÃO é oficial ou afiliado aos desenvolvedores do jogo.',
    'admin.access': 'Acesso Admin',
    'admin.panel': 'Painel Admin',
    'admin.login': 'Login Admin',
    'admin.description': 'Você está atualmente conectado como administrador. Acesse o painel admin para gerenciar o banco de dados e configurações do sistema.',
    'admin.login_description': 'Você é administrador? Acesse o painel admin para gerenciar o banco de dados e configurações do sistema.',
    'values.title': 'Valores de Itens',
    'values.description': 'Encontre os valores de mercado atuais para veículos, roupas e itens.',
    'battlepass.title': 'Battlepass',
    'battlepass.description': 'Acompanhe seu progresso e recompensas do battlepass.',
    'beginner.title': 'Ajuda para Iniciantes',
    'beginner.description': 'Guias essenciais para novos jogadores.',
    'bunker.title': 'Ajuda Bunker',
    'bunker.description': 'Guias de gerenciamento e otimização do bunker.',
    'events.title': 'Eventos',
    'events.description': 'Eventos e atividades do servidor.',
    'lifeinvader.title': 'Modelos LifeInvader',
    'lifeinvader.description': 'Modelos de anúncios pré-formatados para LifeInvader.',
    'improvements.title': 'Melhorias',
    'improvements.description': 'Sugira melhorias e reporte bugs.',
    'suggestions.title': 'Sugestões',
    'suggestions.description': 'Envie suas sugestões para o banco de dados.',
    'treasure.title': 'Helper Tesouro',
    'treasure.description': 'Encontre locais de tesouros e recompensas.',
    'pet.title': 'Timer Animal',
    'pet.description': 'Acompanhe seu cronograma de alimentação de animais.',
    'ai.format_my_ad': 'Formatar meu anúncio',
    'ai.description': 'Use IA para formatar seus anúncios de acordo com as políticas.',
    'community.title': 'Plataforma Impulsionada pela Comunidade',
    'community.built_by_players': '🤝 Construído por Jogadores, para Jogadores',
    'community.built_description': 'Esta plataforma é mantida e atualizada pela comunidade GRP Database. Todos os valores, modelos e recursos são contribuídos por jogadores ativos que entendem as dinâmicas de mercado e as necessidades da comunidade.',
    'community.real_time_data': '📊 Dados de Mercado em Tempo Real',
    'community.data_description': 'Obtenha valores de mercado precisos e atualizados para veículos, roupas e itens. Nossa comunidade garante que os dados reflitam as condições atuais do mercado e ajudem você a tomar decisões comerciais informadas.',
    'navigation.categories': 'Categorias',
    'how_to_join': 'Como participar?',
    'notification.new_update': 'Nova Atualização!',
    'notification.close': 'Fechar popup',
    'community.ai_powered': '🎯 Assistência Baseada em IA',
    'community.ai_description': 'Nosso assistente de IA avançado aprende com o feedback da comunidade para fornecer melhor formatação de anúncios e sugestões. Cada correção ajuda a melhorar o sistema para todos.',
    'community.continuous_improvement': '🔄 Melhoria Contínua',
    'community.improvement_description': 'A plataforma evolui com base no feedback e necessidades da comunidade. Novas funcionalidades, categorias e melhorias são regularmente adicionadas para melhorar sua experiência.',
    'community.tip': '💡 Dica:',
    'community.tip_text': 'Encontrou um valor desatualizado ou tem uma sugestão? Entre em contato com robthemaster no discord para ajudar a melhorar a plataforma para todos!',
    'categories.cars': 'Carros',
    'categories.boats': 'Barcos',
    'categories.planes': 'Aviões',
    'categories.helicopters': 'Helicópteros',
    'categories.clothing_list': 'Lista de Roupas',
    'categories.masks': 'Máscaras',
    'categories.luminous_clothing': 'Roupas Luminosas',
    'categories.items': 'Itens',
    'categories.motorcycles': 'Motocicletas',
    'categories.illegal_items': 'Itens Ilegais',
    'categories.cropped_collection_shirts': 'Camisetas Cropped Collection',
    'categories.denim_jackets': 'Jaquetas Denim',
    'navigation.home': 'Início',
    'navigation.logout': 'Sair',
    'page_titles.battlepass': 'Passe de Batalha',
    'page_titles.bunker_help': 'Ajuda Bunker',
    'page_titles.pet_timer': 'Timer do Pet',
    'page_titles.lifeinvader': 'LifeInvader',
    'page_titles.suggestions': 'Sugestões',
    'page_titles.improvements': 'Melhorias',
    'page_titles.admin_panel': 'Painel Admin',
    'events.school.title': 'Evento Escolar',
    'events.school.description': 'Misturador de cores químicas para eventos escolares.',
    'events.school.chemistry': 'Química',
    'footer.description': 'Fornecendo informações, ferramentas e análises para as comunidades de trading, gaming e relacionadas do GTA Roleplay.',
    'footer.grand_roleplay_trademark': 'Grand Roleplay e suas várias marcas e logos são marcas registradas da Grand Roleplay.',
    'footer.gta_v_trademark': 'Grand Theft Auto V é uma marca registrada da Take-Two Interactive Software Inc.',
    'footer.disclaimer': 'GRP Database não é endossado, patrocinado ou afiliado ao GTA V e Grand Roleplay.',
    'footer.privacy_policy': 'Política de Privacidade',
    'footer.contact': 'Contato',
    'privacy.title': 'Política de Privacidade',
    'privacy.data_collection.title': 'Coleta de Dados',
    'privacy.data_collection.description': 'GRP Database não requer contas de usuário ou informações pessoais para usar o site. Não definimos cookies de rastreamento.',
    'privacy.data_collection.analytics': 'Usamos análises respeitosas à privacidade (alimentadas pelo Vercel) para entender como os visitantes usam o site. Isso pode incluir informações anonimizadas como:',
    'privacy.data_collection.browser_type': 'Tipo de navegador',
    'privacy.data_collection.pages_visited': 'Páginas visitadas',
    'privacy.data_collection.approximate_location': 'Localização aproximada (baseada no endereço IP)',
    'privacy.data_collection.ip_addresses': 'Endereços IP são processados apenas para gerar estatísticas de uso e são anonimizados. Não os usamos para identificar pessoalmente os visitantes.',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.description': 'GRP Database não usa cookies de rastreamento.',
    'privacy.data_sharing.title': 'Compartilhamento de Dados',
    'privacy.data_sharing.description': 'Não vendemos, compartilhamos ou divulgamos suas informações a terceiros. Dados analíticos são usados apenas para melhorar o site.',
    'privacy.contact.title': 'Contato',
    'privacy.contact.description': 'Se você tiver dúvidas sobre esta Política de Privacidade, entre em contato através do formulário de contato ou canais da comunidade.',
    'contact.title': 'Entre em Contato',
    'contact.description': 'Tem uma pergunta ou sugestão? Adoraríamos ouvir você!',
    'contact.email_label': 'Endereço de Email',
    'contact.email_placeholder': 'seu.email@exemplo.com',
    'contact.subject_label': 'Assunto',
    'contact.subject_placeholder': 'Sobre o que é?',
    'contact.message_label': 'Mensagem',
    'contact.message_placeholder': 'Conte-nos o que você pensa...',
    'contact.send_button': 'Enviar Mensagem',
    'contact.sending': 'Enviando...',
    'contact.success_message': 'Obrigado! Sua mensagem foi enviada com sucesso.',
    'contact.error_message': 'Desculpe, houve um erro ao enviar sua mensagem. Tente novamente.',
    'car_customizer.title': 'Configurador de Carros',
    'car_customizer.description': 'Personalize seu carro dos sonhos com modelos inspirados na vida real do GTA V. Escolha cores, peças e acessórios para criar seu veículo perfeito.',
    'car_customizer.select_car': 'Selecionar Modelo de Carro',
    'car_customizer.customize': 'Personalizar Seu Carro',
    'car_customizer.color': 'Cor',
    'car_customizer.parts': 'Peças',
    'car_customizer.spoiler': 'Spoiler',
    'car_customizer.neon': 'Luzes Neon',
    'car_customizer.tint': 'Tintura dos Vidros',
    'car_customizer.no_tint': 'Sem Tintura',
    'car_customizer.light_tint': 'Tintura Clara',
    'car_customizer.medium_tint': 'Tintura Média',
    'car_customizer.dark_tint': 'Tintura Escura',
    'car_customizer.reset': 'Reiniciar',
    'car_customizer.save': 'Salvar Design',
    'car_customizer.total_price': 'Preço Total',
    'car_customizer.price_note': 'Os preços são baseados nos valores do jogo e podem variar',
    'car_customizer.privacy_notice_title': 'Aviso de Privacidade',
    'car_customizer.privacy_notice_text': 'Suas personalizações são armazenadas localmente no seu navegador e não são enviadas para nossos servidores. Nenhum dado pessoal é coletado durante a personalização.',
    'car_customizer.preview': 'Visualização 3D',
    'car_customizer.custom_color': 'Cor Personalizada',
    'car_customizer.underglow': 'Iluminação Inferior',
  },
  jp: {
    'welcome.title': 'GRP Databaseへようこそ',
    'welcome.description': 'GRP Databaseは、GTAロールプレイをより簡単で楽しいものにするために設計された非公式のコミュニティハブです。私たちの目標は、アイテムの価値や衣装オプションから初心者向けのヒントやガイドまで、価値ある情報を一箇所に集めることです。プレイヤーがサーバーでプレイしている間に必要なものを素早く見つけられるよう支援します。',
    'welcome.disclaimer': 'GRP Databaseは公式ではなく、ゲームの開発者とも提携していません。',
    'admin.access': '管理者アクセス',
    'admin.panel': '管理者パネル',
    'admin.login': '管理者ログイン',
    'admin.description': '現在管理者としてログインしています。データベースとシステム設定を管理するには管理者パネルにアクセスしてください。',
    'admin.login_description': 'あなたは管理者ですか？データベースとシステム設定を管理するには管理者パネルにアクセスしてください。',
    'values.title': 'アイテム価値',
    'values.description': '車両、衣装、アイテムの現在の市場価値を確認してください。',
    'battlepass.title': 'バトルパス',
    'battlepass.description': 'バトルパスの進捗と報酬を追跡してください。',
    'beginner.title': '初心者ヘルプ',
    'beginner.description': '新しいプレイヤー向けの基本ガイド。',
    'bunker.title': 'バンカーへルプ',
    'bunker.description': 'バンカー管理と最適化ガイド。',
    'events.title': 'イベント',
    'events.description': 'サーバーイベントとアクティビティ。',
    'lifeinvader.title': 'LifeInvaderテンプレート',
    'lifeinvader.description': 'LifeInvader用の事前フォーマット済み広告テンプレート。',
    'improvements.title': '改善',
    'improvements.description': '改善を提案し、バグを報告してください。',
    'suggestions.title': '提案',
    'suggestions.description': 'データベースへの提案を送信してください。',
    'treasure.title': 'トレジャーヘルパー',
    'treasure.description': '宝物の場所と報酬を見つけてください。',
    'pet.title': 'ペットタイマー',
    'pet.description': 'ペットの餌やりスケジュールを追跡してください。',
    'ai.format_my_ad': '広告をフォーマット',
    'ai.description': 'AIを使用して政策に従って広告をフォーマットしてください。',
    'community.title': 'コミュニティ主導プラットフォーム',
    'community.built_by_players': '🤝 プレイヤーによって、プレイヤーのために構築',
    'community.built_description': 'このプラットフォームはGRP Databaseコミュニティによって維持・更新されています。すべての価値、テンプレート、機能は、市場の動向とコミュニティのニーズを理解しているアクティブなプレイヤーによって提供されています。',
    'community.real_time_data': '📊 リアルタイム市場データ',
    'community.data_description': '車両、衣装、アイテムの正確で最新の市場価値を取得してください。私たちのコミュニティは、データが現在の市場状況を反映し、情報に基づいた取引決定を下すのに役立つことを保証します。',
    'navigation.categories': 'カテゴリ',
    'how_to_join': '参加方法は？',
    'notification.new_update': '新しいアップデート！',
    'notification.close': 'ポップアップを閉じる',
    'community.ai_powered': '🎯 AI支援',
    'community.ai_description': '私たちの高度なAIアシスタントは、コミュニティのフィードバックから学習して、より良い広告フォーマットと提案を提供します。すべての修正がシステム全体の改善に役立ちます。',
    'community.continuous_improvement': '🔄 継続的改善',
    'community.improvement_description': 'プラットフォームは、コミュニティのフィードバックとニーズに基づいて進化します。新しい機能、カテゴリ、改善が定期的に追加され、あなたの体験を向上させます。',
    'community.tip': '💡 ヒント:',
    'community.tip_text': '古い価値を見つけたり、提案がありますか？discordでrobthemasterに連絡して、みんなのためにプラットフォームを改善するのを手伝ってください！',
    'categories.cars': '車',
    'categories.boats': 'ボート',
    'categories.planes': '飛行機',
    'categories.helicopters': 'ヘリコプター',
    'categories.clothing_list': '衣装リスト',
    'categories.masks': 'マスク',
    'categories.luminous_clothing': '光る衣装',
    'categories.items': 'アイテム',
    'categories.motorcycles': 'バイク',
    'categories.illegal_items': '違法アイテム',
    'categories.cropped_collection_shirts': 'Cropped Collection シャツ',
    'categories.denim_jackets': 'デニムジャケット',
    'navigation.home': 'ホーム',
    'navigation.logout': 'ログアウト',
    'page_titles.battlepass': 'バトルパス',
    'page_titles.bunker_help': 'バンカー ヘルプ',
    'page_titles.pet_timer': 'ペット タイマー',
    'page_titles.lifeinvader': 'LifeInvader',
    'page_titles.suggestions': '提案',
    'page_titles.improvements': '改善',
    'page_titles.admin_panel': '管理パネル',
    'events.school.title': '学校イベント',
    'events.school.description': '学校イベント用の化学カラーミキサー。',
    'events.school.chemistry': '化学',
    'footer.description': 'GTAロールプレイの取引、ゲーミング、関連コミュニティに情報、ツール、分析を提供。',
    'footer.grand_roleplay_trademark': 'Grand Roleplayとその各種マークおよびロゴはGrand Roleplayの商標です。',
    'footer.gta_v_trademark': 'Grand Theft Auto VはTake-Two Interactive Software Inc.の商標です。',
    'footer.disclaimer': 'GRP DatabaseはGTA VおよびGrand Roleplayによって承認、スポンサー、または提携されていません。',
    'footer.privacy_policy': 'プライバシーポリシー',
    'footer.contact': 'お問い合わせ',
    'privacy.title': 'プライバシーポリシー',
    'privacy.data_collection.title': 'データ収集',
    'privacy.data_collection.description': 'GRP Databaseは、ウェブサイトを使用するためにユーザーアカウントや個人情報を必要としません。トラッキングクッキーは設定しません。',
    'privacy.data_collection.analytics': 'プライバシーに配慮した分析（Vercel提供）を使用して、訪問者がサイトをどのように使用するかを理解しています。これには以下のような匿名化された情報が含まれる場合があります：',
    'privacy.data_collection.browser_type': 'ブラウザタイプ',
    'privacy.data_collection.pages_visited': '訪問ページ',
    'privacy.data_collection.approximate_location': 'おおよその場所（IPアドレスに基づく）',
    'privacy.data_collection.ip_addresses': 'IPアドレスは使用統計の生成目的でのみ処理され、匿名化されます。訪問者を個人的に特定するために使用することはありません。',
    'privacy.cookies.title': 'クッキー',
    'privacy.cookies.description': 'GRP Databaseはトラッキングクッキーを使用しません。',
    'privacy.data_sharing.title': 'データ共有',
    'privacy.data_sharing.description': 'お客様の情報を第三者に販売、共有、または開示することはありません。分析データはウェブサイトの改善にのみ使用されます。',
    'privacy.contact.title': 'お問い合わせ',
    'privacy.contact.description': 'このプライバシーポリシーについてご質問がある場合は、お問い合わせフォームまたはコミュニティチャンネルを通じてお問い合わせください。',
    'contact.title': 'お問い合わせ',
    'contact.description': 'ご質問やご提案はありますか？お聞かせください！',
    'contact.email_label': 'メールアドレス',
    'contact.email_placeholder': 'your.email@example.com',
    'contact.subject_label': '件名',
    'contact.subject_placeholder': '何についてですか？',
    'contact.message_label': 'メッセージ',
    'contact.message_placeholder': 'お考えをお聞かせください...',
    'contact.send_button': 'メッセージを送信',
    'contact.sending': '送信中...',
    'contact.success_message': 'ありがとうございます！メッセージが正常に送信されました。',
    'contact.error_message': '申し訳ございません。メッセージの送信でエラーが発生しました。もう一度お試しください。',
    'car_customizer.title': 'カスタマイザー',
    'car_customizer.description': 'GTA Vのリアルライフインスパイアされたモデルで夢の車をカスタマイズ。色、パーツ、アクセサリーを選んで完璧な乗り物を作成しましょう。',
    'car_customizer.select_car': '車モデルを選択',
    'car_customizer.customize': '車をカスタマイズ',
    'car_customizer.color': '色',
    'car_customizer.parts': 'パーツ',
    'car_customizer.spoiler': 'スポイラー',
    'car_customizer.neon': 'ネオンライト',
    'car_customizer.tint': 'ウィンドウティント',
    'car_customizer.no_tint': 'ティントなし',
    'car_customizer.light_tint': 'ライトティント',
    'car_customizer.medium_tint': 'ミディアムティント',
    'car_customizer.dark_tint': 'ダークティント',
    'car_customizer.reset': 'リセット',
    'car_customizer.save': 'デザインを保存',
    'car_customizer.total_price': '合計価格',
    'car_customizer.price_note': '価格はゲーム内の値に基づいており、変動する場合があります',
    'car_customizer.privacy_notice_title': 'プライバシー通知',
    'car_customizer.privacy_notice_text': 'カスタマイズはブラウザにローカルに保存され、サーバーに送信されません。カスタマイズ中に個人データは収集されません。',
    'car_customizer.preview': '3Dプレビュー',
    'car_customizer.custom_color': 'カスタムカラー',
    'car_customizer.underglow': 'アンダーグロー',
  },
  ru: {
    'welcome.title': 'Добро пожаловать в GRP Database',
    'welcome.description': 'GRP Database — это неофициальный общественный центр, созданный для того, чтобы сделать GTA Roleplay проще и приятнее. Наша цель — собрать ценную информацию в одном месте — от стоимости предметов и вариантов одежды до советов для новичков и руководств — помогая игрокам быстро найти то, что им нужно, играя на сервере.',
    'welcome.disclaimer': 'GRP Database НЕ является официальным или связанным с разработчиками игры.',
    'admin.access': 'Админ Доступ',
    'admin.panel': 'Админ Панель',
    'admin.login': 'Админ Вход',
    'admin.description': 'Вы в настоящее время вошли в систему как администратор. Получите доступ к админ-панели для управления базой данных и системными настройками.',
    'admin.login_description': 'Вы администратор? Получите доступ к админ-панели для управления базой данных и системными настройками.',
    'values.title': 'Стоимость Предметов',
    'values.description': 'Найдите текущие рыночные цены для транспортных средств, одежды и предметов.',
    'battlepass.title': 'Боевой пропуск',
    'battlepass.description': 'Отслеживайте свой прогресс и награды боевого пропуска.',
    'beginner.title': 'Помощь Новичкам',
    'beginner.description': 'Основные руководства для новых игроков.',
    'bunker.title': 'Помощь Бункеру',
    'bunker.description': 'Руководства по управлению бункером и оптимизации.',
    'events.title': 'События',
    'events.description': 'Серверные события и активности.',
    'lifeinvader.title': 'Шаблоны LifeInvader',
    'lifeinvader.description': 'Предварительно отформатированные шаблоны объявлений для LifeInvader.',
    'improvements.title': 'Улучшения',
    'improvements.description': 'Предложите улучшения и сообщите об ошибках.',
    'suggestions.title': 'Предложения',
    'suggestions.description': 'Отправьте свои предложения для базы данных.',
    'treasure.title': 'Помощник Сокровищ',
    'treasure.description': 'Найдите места сокровищ и награды.',
    'pet.title': 'Таймер Питомца',
    'pet.description': 'Отслеживайте график кормления вашего питомца.',
    'ai.format_my_ad': 'Форматировать мое объявление',
    'ai.description': 'Используйте ИИ для форматирования ваших объявлений согласно политике.',
    'community.title': 'Платформа Сообщества',
    'community.built_by_players': '🤝 Создано Игроками, для Игроков',
    'community.built_description': 'Эта платформа поддерживается и обновляется сообществом GRP Database. Все ценности, шаблоны и функции вносятся активными игроками, которые понимают рыночную динамику и потребности сообщества.',
    'community.real_time_data': '📊 Данные Рынка в Реальном Времени',
    'community.data_description': 'Получайте точные, актуальные рыночные цены для транспортных средств, одежды и предметов. Наше сообщество гарантирует, что данные отражают текущие рыночные условия и помогают вам принимать обоснованные торговые решения.',
    'navigation.categories': 'Категории',
    'how_to_join': 'Как присоединиться?',
    'notification.new_update': 'Новое Обновление!',
    'notification.close': 'Закрыть popup',
    'community.ai_powered': '🎯 ИИ-Помощь',
    'community.ai_description': 'Наш продвинутый ИИ-ассистент учится на отзывах сообщества, чтобы предоставлять лучшее форматирование объявлений и предложения. Каждая коррекция помогает улучшить систему для всех.',
    'community.continuous_improvement': '🔄 Непрерывное Улучшение',
    'community.improvement_description': 'Платформа развивается на основе отзывов и потребностей сообщества. Новые функции, категории и улучшения регулярно добавляются для улучшения вашего опыта.',
    'community.tip': '💡 Совет:',
    'community.tip_text': 'Нашли устаревшую стоимость или есть предложение? Свяжитесь с robthemaster в discord, чтобы помочь улучшить платформу для всех!',
    'categories.cars': 'Автомобили',
    'categories.boats': 'Лодки',
    'categories.planes': 'Самолеты',
    'categories.helicopters': 'Вертолеты',
    'categories.clothing_list': 'Список Одежды',
    'categories.masks': 'Маски',
    'categories.luminous_clothing': 'Светящаяся Одежда',
    'categories.items': 'Предметы',
    'categories.motorcycles': 'Мотоциклы',
    'categories.illegal_items': 'Незаконные Предметы',
    'categories.cropped_collection_shirts': 'Cropped Collection Футболки',
    'categories.denim_jackets': 'Джинсовые Куртки',
    'navigation.home': 'Главная',
    'navigation.logout': 'Выйти',
    'page_titles.battlepass': 'Боевой Пропуск',
    'page_titles.bunker_help': 'Помощь Бункеру',
    'page_titles.pet_timer': 'Таймер Питомца',
    'page_titles.lifeinvader': 'LifeInvader',
    'page_titles.suggestions': 'Предложения',
    'page_titles.improvements': 'Улучшения',
    'page_titles.admin_panel': 'Админ Панель',
    'events.school.title': 'Школьное Событие',
    'events.school.description': 'Химический смеситель цветов для школьных событий.',
    'events.school.chemistry': 'Химия',
    'footer.description': 'Предоставление информации, инструментов и аналитики для сообществ торговли, гейминга и связанных с GTA Roleplay.',
    'footer.grand_roleplay_trademark': 'Grand Roleplay и его различные знаки и логотипы являются товарными знаками Grand Roleplay.',
    'footer.gta_v_trademark': 'Grand Theft Auto V является товарным знаком Take-Two Interactive Software Inc.',
    'footer.disclaimer': 'GRP Database не одобрен, не спонсируется и не связан с GTA V и Grand Roleplay.',
    'footer.privacy_policy': 'Политика конфиденциальности',
    'footer.contact': 'Контакты',
    'privacy.title': 'Политика конфиденциальности',
    'privacy.data_collection.title': 'Сбор данных',
    'privacy.data_collection.description': 'GRP Database не требует пользовательских аккаунтов или личной информации для использования веб-сайта. Мы не устанавливаем отслеживающие файлы cookie.',
    'privacy.data_collection.analytics': 'Мы используем аналитику, дружелюбную к конфиденциальности (от Vercel), чтобы понять, как посетители используют сайт. Это может включать анонимизированную информацию, такую как:',
    'privacy.data_collection.browser_type': 'Тип браузера',
    'privacy.data_collection.pages_visited': 'Посещенные страницы',
    'privacy.data_collection.approximate_location': 'Приблизительное местоположение (на основе IP-адреса)',
    'privacy.data_collection.ip_addresses': 'IP-адреса обрабатываются только для генерации статистики использования и анонимизируются. Мы не используем их для личной идентификации посетителей.',
    'privacy.cookies.title': 'Файлы cookie',
    'privacy.cookies.description': 'GRP Database не использует отслеживающие файлы cookie.',
    'privacy.data_sharing.title': 'Обмен данными',
    'privacy.data_sharing.description': 'Мы не продаем, не делимся и не раскрываем вашу информацию третьим лицам. Аналитические данные используются только для улучшения веб-сайта.',
    'privacy.contact.title': 'Контакты',
    'privacy.contact.description': 'Если у вас есть вопросы об этой Политике конфиденциальности, пожалуйста, свяжитесь с нами через форму обратной связи или каналы сообщества.',
    'contact.title': 'Свяжитесь с нами',
    'contact.description': 'У вас есть вопрос или предложение? Мы хотели бы услышать от вас!',
    'contact.email_label': 'Адрес электронной почты',
    'contact.email_placeholder': 'your.email@example.com',
    'contact.subject_label': 'Тема',
    'contact.subject_placeholder': 'О чем это?',
    'contact.message_label': 'Сообщение',
    'contact.message_placeholder': 'Расскажите нам, что вы думаете...',
    'contact.send_button': 'Отправить сообщение',
    'contact.sending': 'Отправка...',
    'contact.success_message': 'Спасибо! Ваше сообщение было успешно отправлено.',
    'contact.error_message': 'Извините, произошла ошибка при отправке вашего сообщения. Пожалуйста, попробуйте еще раз.',
    'car_customizer.title': 'Конфигуратор автомобилей',
    'car_customizer.description': 'Настройте автомобиль своей мечты с моделями, вдохновленными реальной жизнью из GTA V. Выберите цвета, детали и аксессуары, чтобы создать свой идеальный автомобиль.',
    'car_customizer.select_car': 'Выбрать модель автомобиля',
    'car_customizer.customize': 'Настроить ваш автомобиль',
    'car_customizer.color': 'Цвет',
    'car_customizer.parts': 'Детали',
    'car_customizer.spoiler': 'Спойлер',
    'car_customizer.neon': 'Неоновые огни',
    'car_customizer.tint': 'Тонировка стекол',
    'car_customizer.no_tint': 'Без тонировки',
    'car_customizer.light_tint': 'Светлая тонировка',
    'car_customizer.medium_tint': 'Средняя тонировка',
    'car_customizer.dark_tint': 'Темная тонировка',
    'car_customizer.reset': 'Сбросить',
    'car_customizer.save': 'Сохранить дизайн',
    'car_customizer.total_price': 'Общая цена',
    'car_customizer.price_note': 'Цены основаны на игровых значениях и могут варьироваться',
    'car_customizer.privacy_notice_title': 'Уведомление о конфиденциальности',
    'car_customizer.privacy_notice_text': 'Ваши настройки сохраняются локально в вашем браузере и не отправляются на наши серверы. При настройке личные данные не собираются.',
    'car_customizer.preview': '3D Предпросмотр',
    'car_customizer.custom_color': 'Пользовательский Цвет',
    'car_customizer.underglow': 'Подсветка Снизу',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('grp-language') as Language;
    if (savedLanguage && LANGUAGES.some(lang => lang.code === savedLanguage)) {
      setLanguage(savedLanguage);
      return;
    }

    const browserLang = navigator.language.split('-')[0];
    const supportedBrowserLang = LANGUAGES.find(lang =>
      browserLang === lang.code ||
      (browserLang === 'pt' && lang.code === 'pt') ||
      (browserLang === 'zh' && lang.code === 'jp')
    )?.code;

    if (supportedBrowserLang) {
      setLanguage(supportedBrowserLang);
      return;
    }

    setLanguage('en');
  }, []);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('grp-language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
